---
apiVersion: v1
kind: Pod
metadata:
  namespace: cicd
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
spec:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/cicd-cpu
      operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/cicd-cpu
                operator: In
                values:
                  - ""
  containers:
    - name: builder
      image: "066141165427.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins/go-agent:1.25-ubuntu24-2025-47"
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 500Mi
      volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
